#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# First parameter
filter=""
dry="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

log()
{
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "Execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

   "$@"
}

log "-------------- dev-env ----------------"

# default XDG_CONFIG_HOME to ~/.config
: "${XDG_CONFIG_HOME:=$HOME/.config}"

log "Copying configs into: $XDG_CONFIG_HOME"

copy_dir() {
    from=$1
    to=$2

    pushd $from > /dev/null
    dirs=$(gfind . -maxdepth 1 -mindepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)

    execute rm $to/$name
    execute cp $from $to/$name
}

copy_dir .config $XDG_CONFIG_HOME
copy_file .specialconfig $HOME

