#!/usr/bin/env bash

DIR=$HOME/Documents/neovim
if [ ! -d "$DIR" ]; then
  mkdir -p "$DIR"
fi


version="v0.11.1"
if [ ! -z $NVIM_VERSION ]; then
    version="$NVIM_VERSION"
fi

echo "version: \"$version\""

# neovim btw
git clone https://github.com/neovim/neovim.git $DIR

sudo apt -y install cmake gettext lua5.1 liblua5.1-0-dev

make CMAKE_BUILD_TYPE=Release
sudo make install

